RpaUi/Areas/Client/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RpaData.DataContext;
using RpaData.Models;

namespace RpaUi.Areas.Client.Controllers
{
    [Authorize]
    [Area("Client")]
    public class InvoicesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InvoicesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Client/Invoices
        public async Task<IActionResult> Index()
        {
            var clientId = Convert.ToInt32(User.FindFirst("ClientId").Value);
            int Id = Convert.ToInt32(clientId);
            var applicationDbContext = _context.tblInvoiceClient
                                        .Include(t => t.tblInvoices)
                                        .ThenInclude(t => t.InvoiceType)
                                        .Include(t => t.tblInvoices)
                                        .ThenInclude(t=>t.tblPayments)
                                        .Where(c=>c.tblPharmacistsId == Id);

            var payments = _context.tblPayments.Include(t => t.Invoice).Where(c => c.tblPharmacistsId== clientId);
            ViewBag.Payments = payments;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Client/Invoices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblInvoices = await _context.tblInvoiceClient
                                        .Include(t => t.tblInvoices)
                                        .ThenInclude(t => t.InvoiceType)
                                        .Include(t => t.tblInvoices)
                                        .ThenInclude(t => t.tblPayments)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblInvoices == null)
            {
                return NotFound();
            }

            return View(tblInvoices);
        }

        // GET: Client/Invoices/Create
        public IActionResult Create()
        {
            ViewData["InvoiceTypeId"] = new SelectList(_context.tblCodes, "Id", "Id");
            return View();
        }

        // POST: Client/Invoices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Amount,InvoiceTypeId,DueDate,InvoiceComment,Id,Created")] tblInvoices tblInvoices)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblInvoices);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["InvoiceTypeId"] = new SelectList(_context.tblCodes, "Id", "Id", tblInvoices.InvoiceTypeId);
            return View(tblInvoices);
        }

        // GET: Client/Invoices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblInvoices = await _context.tblInvoices.FindAsync(id);
            if (tblInvoices == null)
            {
                return NotFound();
            }
            ViewData["InvoiceTypeId"] = new SelectList(_context.tblCodes, "Id", "Id", tblInvoices.InvoiceTypeId);
            return View(tblInvoices);
        }

        // POST: Client/Invoices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Amount,InvoiceTypeId,DueDate,InvoiceComment,Id,Created")] tblInvoices tblInvoices)
        {
            if (id != tblInvoices.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblInvoices);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblInvoicesExists(tblInvoices.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["InvoiceTypeId"] = new SelectList(_context.tblCodes, "Id", "Id", tblInvoices.InvoiceTypeId);
            return View(tblInvoices);
        }

        // GET: Client/Invoices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblInvoices = await _context.tblInvoices
                .Include(t => t.InvoiceType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblInvoices == null)
            {
                return NotFound();
            }

            return View(tblInvoices);
        }

        // POST: Client/Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblInvoices = await _context.tblInvoices.FindAsync(id);
            _context.tblInvoices.Remove(tblInvoices);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Payment(IFormCollection formCollection)
        {
            var Id = Convert.ToInt32(formCollection["Id"]);
            var amountPaid = formCollection["amount_due"];
            var paymentDetails = formCollection["payment_details"];
            var paymentDate = formCollection["payment_date"];
            var paymentTypeId = Convert.ToInt32(formCollection["payment_type_id"]);
            var paymentFileName = "";

            if (Request.Form.Files.Count() > 0)
            {
                IFormFile file = Request.Form.Files[0];
                var filename = Guid.NewGuid().ToString() + Path.GetExtension(Path.GetFileName(file.FileName));
                paymentFileName = filename;

                string uploadPath = @"wwwroot\Uploads";
                if (!Directory.Exists(Path.Combine(uploadPath)))
                {
                    // If it doesn't exist, create the directory
                    Directory.CreateDirectory(Path.Combine(uploadPath));
                }
                var filePath = uploadPath + "/" + filename;

                await file.CopyToAsync(new FileStream(filePath, FileMode.Create));
            }

            var tblInvoices = await _context.tblInvoices.FindAsync(Id);

            tblPayments payments = new tblPayments();
            payments.AmountPaid = Convert.ToDecimal(amountPaid);
            payments.tblPharmacistsId = Convert.ToInt32(User.FindFirst("ClientId").Value);
            payments.PayDate = Convert.ToDateTime(paymentDate);
            payments.PaymentComment = paymentDetails;
            payments.Created = DateTime.Now;
            payments.PaymentTypeId = paymentTypeId;
            payments.ProofOfPayment = paymentFileName;
            payments.InvoiceId = Id;

            _context.Add(payments);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool tblInvoicesExists(int id)
        {
            return _context.tblInvoices.Any(e => e.Id == id);
        }
    }
}

RpaUi/Areas/Client/Views/Invoices/Create.cshtml
@model RpaData.Models.tblInvoices

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>tblInvoices</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvoiceTypeId" class="control-label"></label>
                <select asp-for="InvoiceTypeId" class ="form-control" asp-items="ViewBag.InvoiceTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvoiceComment" class="control-label"></label>
                <input asp-for="InvoiceComment" class="form-control" />
                <span asp-validation-for="InvoiceComment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RpaUi/Areas/Client/Views/Invoices/Delete.cshtml
@model RpaData.Models.tblInvoices

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblInvoices</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceComment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InvoiceComment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InvoiceType.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RpaUi/Areas/Client/Views/Invoices/Details.cshtml
@model RpaData.Models.tblInvoicesClient
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

    
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3>INV-@Model.Id.ToString("000") - Details</h3>
                </div><!-- /.col -->
                <div class="col-sm-6">
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
<div class="card">
    <div class="card-body">
        <div>
            <a asp-action="Index" class="btn btn-sm btn-outline-success">  <i class="fas fa-long-arrow-alt-left"></i> Back to List</a> 
        </div>
        <div>
            <hr />
            <dl class="row">
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.tblInvoices.Amount)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.tblInvoices.Amount)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.tblInvoices.DueDate)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.tblInvoices.DueDate)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.tblInvoices.InvoiceComment)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.tblInvoices.InvoiceComment)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.tblInvoices.InvoiceType)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.tblInvoices.InvoiceType.CodeName)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Created)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Created)
                </dd>
            </dl>
        </div>
    </div>
    <div class="card-footer">
        <div>
            <a asp-action="Index" class="btn btn-sm btn-outline-success">  <i class="fas fa-long-arrow-alt-left"></i> Back to List</a>
        </div>
    </div>
</div>

RpaUi/Areas/Client/Views/Invoices/Edit.cshtml
@model RpaData.Models.tblInvoices

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>tblInvoices</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvoiceTypeId" class="control-label"></label>
                <select asp-for="InvoiceTypeId" class="form-control" asp-items="ViewBag.InvoiceTypeId"></select>
                <span asp-validation-for="InvoiceTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvoiceComment" class="control-label"></label>
                <input asp-for="InvoiceComment" class="form-control" />
                <span asp-validation-for="InvoiceComment" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RpaUi/Areas/Client/Views/Invoices/Index.cshtml
@model IEnumerable<RpaData.Models.tblInvoicesClient>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}


<div class="content-header">
    <div class="container">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h2>Invoices</h2>
            </div><!-- /.col -->
            <div class="col-sm-6">
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<div class="card">
    <div class="card-body">
        <table id="example2" class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Invoice List
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            <b> Invoice No. </b> INV-@item.tblInvoices.Id.ToString("000") <br />
                            <b>Amount Due : </b> @Html.DisplayFor(modelItem => item.tblInvoices.Amount) <br />
                            <b> Due Date : </b> @Html.DisplayFor(modelItem => item.tblInvoices.DueDate) <br />
                            <b>Item : </b>@Html.DisplayFor(modelItem => item.tblInvoices.InvoiceType.CodeName) <br />

                            <hr />
                            @if (item.tblInvoices.tblPayments.Count() > 0)

                            {
                                <b>Payment Details</b>
                                <p>
                                    <span>@item.tblInvoices.tblPayments.FirstOrDefault().AmountPaid.ToString("###,##.00")</span><br />
                                    <span>@(item.tblInvoices.tblPayments.FirstOrDefault().PaymentStatus ? "Paid" : "Pending Confirmation")</span>
                                </p>
                            }
                            else
                            {
                                <a href="#addPosition" data-toggle="modal" data-target="#addPayment" data-id='["@item.tblInvoices.Id","@item.tblInvoices.Amount","@item.tblInvoices.InvoiceTypeId","@item.tblInvoices.InvoiceType.CodeName"]' class="addPosition btn btn-sm btn-outline-primary">
                                    <i class="fas fa-money-check-alt"></i> Make Payment
                                </a>
                            }

                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-outline-success"><i class="fas fa-folder-open"></i> View Details</a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="addPaym" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


<div id="addPayment" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title text-center">Add Payment</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            @using (Html.BeginForm("Payment", "Invoices", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

                    <div class="form-group form-group-sm">

                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <label for="kinaddress">Amount Paid:</label>
                                <input type="text" class="form-control" id="amount_due" name="amount_due" />
                                <input type="hidden" class="form-control" id="Id" name="Id" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <label for="kinaddress">Invoice Type:</label>
                                <input type="text" class="form-control" id="invoice_type" name="invoice_type" disabled />
                                <input type="hidden" class="form-control" id="payment_type_id" name="payment_type_id" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <label for="contract">Payment Date</label>
                                <input type="date" class="form-control" id="payment_date" name="payment_date" required />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <label for="contract">Proof of Payment</label>
                                <input type="file" class="form-control" id="proof_of_payment" name="proof_of_payment" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <label for="cntrct_desc">Payment Details:</label>
                                <textarea class="form-control" rows="5" id="payment_details" name="payment_details" placeholder="Eg. From CBZ account 12345677"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 col-md-12">
                            <br />
                            <input type="submit" class="btn btn-success btn-sm form-control" value="Save">
                        </div>
                    </div>
                </div>

                <div class="modal-footer">

                </div>
            }

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $(".addPosition").click(function () {
            var my_id_value = $(this).data('id');
            $("#addPayment").find('input[name="Id"]').val(my_id_value[0]);
            $("#addPayment").find('input[name="amount_due"]').val(my_id_value[1]);
            $("#addPayment").find('input[name="payment_type_id"]').val(my_id_value[2]);
            $("#addPayment").find('input[name="invoice_type"]').val(my_id_value[3]);
        })
    });
</script>